version: "3.4"

# Development environment override
services:
  php:
    image: ${PROJECT}-php-dev
    volumes:
      - ./app/:/srv/app
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      - host.docker.internal:host-gateway

  caddy:
    volumes:
      - ./app/public:/srv/app/public:ro
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro

  ###> doctrine/doctrine-bundle ###
  database:
    volumes:
      - ./docker/mysql/dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3306"
  ###< doctrine/doctrine-bundle ###

  webpack:
    image: ${PROJECT}-webpack
    volumes:
      - ./app/public:/srv/app/public
      - ./app/assets:/srv/app/assets
    working_dir: /srv/app
    command: "yarn start"
